version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@dev:alpha

mvn-release-prepare-command: &mvn-release-prepare-command-dryRun
  # add -DdryRun=true
  mvn-release-prepare-command: mvn --batch-mode release:prepare -DdryRun=true

mvn-release-perform-command: &mvn-release-perform-command-dryRun
  # add -DdryRun=true
  mvn-release-perform-command: mvn --batch-mode release:perform -DdryRun=true -s .circleci/.maven.xml

workflows:
  main:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          <<: *mvn-release-prepare-command-dryRun
          <<: *mvn-release-perform-command-dryRun

  live:
    jobs:
      - circleci-maven-release-orb/run-maven-release
