version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@dev:alpha

mvn-release-prepare-command: &mvn-release-prepare-command-dryRun
  # adds -DdryRun=true
  mvn-release-prepare-command: mvn --batch-mode release:prepare -DscmCommentPrefix="[skip ci] [maven-release-plugin] " -DdryRun=true

mvn-release-perform-command: &mvn-release-perform-command-dryRun
  # adds -DdryRun=true
  mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml -DdryRun=true

workflows:
  dry-run:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          <<: *mvn-release-prepare-command-dryRun
          <<: *mvn-release-perform-command-dryRun
          context: dan-test

  run-release:
    jobs:
      - approve-release:
          type: approval

      - circleci-maven-release-orb/run-maven-release:
          ssh-fingerprints: "16:27:fe:e2:82:31:2c:8f:af:8a:06:45:13:3a:27:d5"
          context: dan-test
          requires:
            - approve-release
          filters:
            branches:
              only: master
